version: '3.9'
services:
  app: 
    container_name: java_app
    image: 'gestion-usuarios:1.0'
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=bogota
      - SPRING_DATASOURCE_PASSWORD=password
